version: "3.9"

services:

  aapimysql:
    container_name: aapimysql
    image: mysql:8
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./volumes/mysqldb:/var/lib/mysql
      - ./docker/mysql_installer/master/master.cnf:/etc/mysql/conf.d/master.cnf:ro
      - ./docker/mysqlseed:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=app_Password
      - MYSQL_PASSWORD=app_Password
      - MYSQL_USER=app_User
      - MYSQL_DATABASE=app
    healthcheck:
      test: mysqladmin --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD ping
      interval: 5s
      timeout: 3s
      retries: 10
    logging:
      driver: none
    networks:
      - microservice_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

