// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: services/user/protos/faiss/v1/faiss.proto

package faiss

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusCode int32

const (
	StatusCode_ENGINE_ERROR                      StatusCode = 0
	StatusCode_SUCCESS                           StatusCode = 1
	StatusCode_BAD_IMAGE                         StatusCode = 2
	StatusCode_BAD_VECTOR                        StatusCode = 3
	StatusCode_IMAGE_REGISTERED_FOR_ANOTHER_USER StatusCode = 4
	StatusCode_FOUND                             StatusCode = 5
	StatusCode_NOT_FOUND                         StatusCode = 6
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0: "ENGINE_ERROR",
		1: "SUCCESS",
		2: "BAD_IMAGE",
		3: "BAD_VECTOR",
		4: "IMAGE_REGISTERED_FOR_ANOTHER_USER",
		5: "FOUND",
		6: "NOT_FOUND",
	}
	StatusCode_value = map[string]int32{
		"ENGINE_ERROR":                      0,
		"SUCCESS":                           1,
		"BAD_IMAGE":                         2,
		"BAD_VECTOR":                        3,
		"IMAGE_REGISTERED_FOR_ANOTHER_USER": 4,
		"FOUND":                             5,
		"NOT_FOUND":                         6,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_services_user_protos_faiss_v1_faiss_proto_enumTypes[0].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_services_user_protos_faiss_v1_faiss_proto_enumTypes[0]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_services_user_protos_faiss_v1_faiss_proto_rawDescGZIP(), []int{0}
}

type Vector struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VectorId string    `protobuf:"bytes,1,opt,name=vector_id,json=vectorId,proto3" json:"vector_id,omitempty"` // Optional
	Data     []float64 `protobuf:"fixed64,2,rep,packed,name=data,proto3" json:"data,omitempty"`
}

func (x *Vector) Reset() {
	*x = Vector{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_user_protos_faiss_v1_faiss_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector) ProtoMessage() {}

func (x *Vector) ProtoReflect() protoreflect.Message {
	mi := &file_services_user_protos_faiss_v1_faiss_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector.ProtoReflect.Descriptor instead.
func (*Vector) Descriptor() ([]byte, []int) {
	return file_services_user_protos_faiss_v1_faiss_proto_rawDescGZIP(), []int{0}
}

func (x *Vector) GetVectorId() string {
	if x != nil {
		return x.VectorId
	}
	return ""
}

func (x *Vector) GetData() []float64 {
	if x != nil {
		return x.Data
	}
	return nil
}

// The request to register a user and his/her face images
type VectorEnrollmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// User ID, managed by other service
	UserUid string `protobuf:"bytes,1,opt,name=user_uid,json=userUid,proto3" json:"user_uid,omitempty"` // (Required)
	// One user can have many face images
	Vectors []*Vector `protobuf:"bytes,2,rep,name=vectors,proto3" json:"vectors,omitempty"` // (Required)
}

func (x *VectorEnrollmentRequest) Reset() {
	*x = VectorEnrollmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_user_protos_faiss_v1_faiss_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VectorEnrollmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorEnrollmentRequest) ProtoMessage() {}

func (x *VectorEnrollmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_user_protos_faiss_v1_faiss_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorEnrollmentRequest.ProtoReflect.Descriptor instead.
func (*VectorEnrollmentRequest) Descriptor() ([]byte, []int) {
	return file_services_user_protos_faiss_v1_faiss_proto_rawDescGZIP(), []int{1}
}

func (x *VectorEnrollmentRequest) GetUserUid() string {
	if x != nil {
		return x.UserUid
	}
	return ""
}

func (x *VectorEnrollmentRequest) GetVectors() []*Vector {
	if x != nil {
		return x.Vectors
	}
	return nil
}

// The request to delete all face ids of the given user_uid
type VectorDeletionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageIds []string `protobuf:"bytes,1,rep,name=image_ids,json=imageIds,proto3" json:"image_ids,omitempty"` // Delete by image id
	UserUid  string   `protobuf:"bytes,2,opt,name=user_uid,json=userUid,proto3" json:"user_uid,omitempty"`    // Or delete by user id
}

func (x *VectorDeletionRequest) Reset() {
	*x = VectorDeletionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_user_protos_faiss_v1_faiss_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VectorDeletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorDeletionRequest) ProtoMessage() {}

func (x *VectorDeletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_user_protos_faiss_v1_faiss_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorDeletionRequest.ProtoReflect.Descriptor instead.
func (*VectorDeletionRequest) Descriptor() ([]byte, []int) {
	return file_services_user_protos_faiss_v1_faiss_proto_rawDescGZIP(), []int{2}
}

func (x *VectorDeletionRequest) GetImageIds() []string {
	if x != nil {
		return x.ImageIds
	}
	return nil
}

func (x *VectorDeletionRequest) GetUserUid() string {
	if x != nil {
		return x.UserUid
	}
	return ""
}

type VectorEnrollmentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    StatusCode `protobuf:"varint,1,opt,name=code,proto3,enum=faiss.StatusCode" json:"code,omitempty"`
	Message string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Optional message from server
}

func (x *VectorEnrollmentResponse) Reset() {
	*x = VectorEnrollmentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_user_protos_faiss_v1_faiss_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VectorEnrollmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorEnrollmentResponse) ProtoMessage() {}

func (x *VectorEnrollmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_user_protos_faiss_v1_faiss_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorEnrollmentResponse.ProtoReflect.Descriptor instead.
func (*VectorEnrollmentResponse) Descriptor() ([]byte, []int) {
	return file_services_user_protos_faiss_v1_faiss_proto_rawDescGZIP(), []int{3}
}

func (x *VectorEnrollmentResponse) GetCode() StatusCode {
	if x != nil {
		return x.Code
	}
	return StatusCode_ENGINE_ERROR
}

func (x *VectorEnrollmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type VectorSearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vectors []*Vector `protobuf:"bytes,1,rep,name=vectors,proto3" json:"vectors,omitempty"`
}

func (x *VectorSearchRequest) Reset() {
	*x = VectorSearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_user_protos_faiss_v1_faiss_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VectorSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorSearchRequest) ProtoMessage() {}

func (x *VectorSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_user_protos_faiss_v1_faiss_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorSearchRequest.ProtoReflect.Descriptor instead.
func (*VectorSearchRequest) Descriptor() ([]byte, []int) {
	return file_services_user_protos_faiss_v1_faiss_proto_rawDescGZIP(), []int{4}
}

func (x *VectorSearchRequest) GetVectors() []*Vector {
	if x != nil {
		return x.Vectors
	}
	return nil
}

type VectorSearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    StatusCode `protobuf:"varint,1,opt,name=code,proto3,enum=faiss.StatusCode" json:"code,omitempty"`
	Message string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UserUid string     `protobuf:"bytes,3,opt,name=user_uid,json=userUid,proto3" json:"user_uid,omitempty"` // Empty when user image not found
	ImageId string     `protobuf:"bytes,4,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"` // The image_id of the first mached image
	Score   float64    `protobuf:"fixed64,5,opt,name=score,proto3" json:"score,omitempty"`                  // The matching score for debugging purpose
}

func (x *VectorSearchResponse) Reset() {
	*x = VectorSearchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_user_protos_faiss_v1_faiss_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VectorSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorSearchResponse) ProtoMessage() {}

func (x *VectorSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_user_protos_faiss_v1_faiss_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorSearchResponse.ProtoReflect.Descriptor instead.
func (*VectorSearchResponse) Descriptor() ([]byte, []int) {
	return file_services_user_protos_faiss_v1_faiss_proto_rawDescGZIP(), []int{5}
}

func (x *VectorSearchResponse) GetCode() StatusCode {
	if x != nil {
		return x.Code
	}
	return StatusCode_ENGINE_ERROR
}

func (x *VectorSearchResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VectorSearchResponse) GetUserUid() string {
	if x != nil {
		return x.UserUid
	}
	return ""
}

func (x *VectorSearchResponse) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *VectorSearchResponse) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type VectorDeletionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    StatusCode `protobuf:"varint,1,opt,name=code,proto3,enum=faiss.StatusCode" json:"code,omitempty"`
	Message string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Optional message from server
}

func (x *VectorDeletionResponse) Reset() {
	*x = VectorDeletionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_user_protos_faiss_v1_faiss_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VectorDeletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorDeletionResponse) ProtoMessage() {}

func (x *VectorDeletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_user_protos_faiss_v1_faiss_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorDeletionResponse.ProtoReflect.Descriptor instead.
func (*VectorDeletionResponse) Descriptor() ([]byte, []int) {
	return file_services_user_protos_faiss_v1_faiss_proto_rawDescGZIP(), []int{6}
}

func (x *VectorDeletionResponse) GetCode() StatusCode {
	if x != nil {
		return x.Code
	}
	return StatusCode_ENGINE_ERROR
}

func (x *VectorDeletionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_services_user_protos_faiss_v1_faiss_proto protoreflect.FileDescriptor

var file_services_user_protos_faiss_v1_faiss_proto_rawDesc = []byte{
	0x0a, 0x29, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x66, 0x61, 0x69, 0x73, 0x73, 0x2f, 0x76, 0x31, 0x2f,
	0x66, 0x61, 0x69, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x66, 0x61, 0x69,
	0x73, 0x73, 0x22, 0x39, 0x0a, 0x06, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x1b, 0x0a, 0x09,
	0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x01, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x5d, 0x0a,
	0x17, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x55, 0x69, 0x64, 0x12, 0x27, 0x0a, 0x07, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x66, 0x61, 0x69, 0x73, 0x73, 0x2e, 0x56, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x52, 0x07, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x22, 0x4f, 0x0a, 0x15,
	0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x69,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x49,
	0x64, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x55, 0x69, 0x64, 0x22, 0x5b, 0x0a,
	0x18, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x66, 0x61, 0x69, 0x73, 0x73, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x3e, 0x0a, 0x13, 0x56, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x27, 0x0a, 0x07, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x66, 0x61, 0x69, 0x73, 0x73, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x52, 0x07, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x22, 0xa3, 0x01, 0x0a, 0x14, 0x56,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x11, 0x2e, 0x66, 0x61, 0x69, 0x73, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x75, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x55, 0x69, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63,
	0x6f, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65,
	0x22, 0x59, 0x0a, 0x16, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x66, 0x61, 0x69, 0x73, 0x73,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0x8b, 0x01, 0x0a, 0x0a,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x45, 0x4e,
	0x47, 0x49, 0x4e, 0x45, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07,
	0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x42, 0x41, 0x44,
	0x5f, 0x49, 0x4d, 0x41, 0x47, 0x45, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x42, 0x41, 0x44, 0x5f,
	0x56, 0x45, 0x43, 0x54, 0x4f, 0x52, 0x10, 0x03, 0x12, 0x25, 0x0a, 0x21, 0x49, 0x4d, 0x41, 0x47,
	0x45, 0x5f, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x45, 0x52, 0x45, 0x44, 0x5f, 0x46, 0x4f, 0x52,
	0x5f, 0x41, 0x4e, 0x4f, 0x54, 0x48, 0x45, 0x52, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x10, 0x04, 0x12,
	0x09, 0x0a, 0x05, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x05, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f,
	0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x06, 0x32, 0xe0, 0x01, 0x0a, 0x09, 0x56, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x41, 0x50, 0x49, 0x12, 0x49, 0x0a, 0x06, 0x45, 0x6e, 0x72, 0x6f, 0x6c,
	0x6c, 0x12, 0x1e, 0x2e, 0x66, 0x61, 0x69, 0x73, 0x73, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1f, 0x2e, 0x66, 0x61, 0x69, 0x73, 0x73, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x41, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x1a, 0x2e, 0x66,
	0x61, 0x69, 0x73, 0x73, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x66, 0x61, 0x69, 0x73, 0x73,
	0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12,
	0x1c, 0x2e, 0x66, 0x61, 0x69, 0x73, 0x73, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e,
	0x66, 0x61, 0x69, 0x73, 0x73, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x25, 0x5a, 0x23,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x66, 0x61, 0x69, 0x73, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x66, 0x61,
	0x69, 0x73, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_user_protos_faiss_v1_faiss_proto_rawDescOnce sync.Once
	file_services_user_protos_faiss_v1_faiss_proto_rawDescData = file_services_user_protos_faiss_v1_faiss_proto_rawDesc
)

func file_services_user_protos_faiss_v1_faiss_proto_rawDescGZIP() []byte {
	file_services_user_protos_faiss_v1_faiss_proto_rawDescOnce.Do(func() {
		file_services_user_protos_faiss_v1_faiss_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_user_protos_faiss_v1_faiss_proto_rawDescData)
	})
	return file_services_user_protos_faiss_v1_faiss_proto_rawDescData
}

var file_services_user_protos_faiss_v1_faiss_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_services_user_protos_faiss_v1_faiss_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_services_user_protos_faiss_v1_faiss_proto_goTypes = []interface{}{
	(StatusCode)(0),                  // 0: faiss.StatusCode
	(*Vector)(nil),                   // 1: faiss.Vector
	(*VectorEnrollmentRequest)(nil),  // 2: faiss.VectorEnrollmentRequest
	(*VectorDeletionRequest)(nil),    // 3: faiss.VectorDeletionRequest
	(*VectorEnrollmentResponse)(nil), // 4: faiss.VectorEnrollmentResponse
	(*VectorSearchRequest)(nil),      // 5: faiss.VectorSearchRequest
	(*VectorSearchResponse)(nil),     // 6: faiss.VectorSearchResponse
	(*VectorDeletionResponse)(nil),   // 7: faiss.VectorDeletionResponse
}
var file_services_user_protos_faiss_v1_faiss_proto_depIdxs = []int32{
	1, // 0: faiss.VectorEnrollmentRequest.vectors:type_name -> faiss.Vector
	0, // 1: faiss.VectorEnrollmentResponse.code:type_name -> faiss.StatusCode
	1, // 2: faiss.VectorSearchRequest.vectors:type_name -> faiss.Vector
	0, // 3: faiss.VectorSearchResponse.code:type_name -> faiss.StatusCode
	0, // 4: faiss.VectorDeletionResponse.code:type_name -> faiss.StatusCode
	2, // 5: faiss.VectorAPI.Enroll:input_type -> faiss.VectorEnrollmentRequest
	5, // 6: faiss.VectorAPI.Search:input_type -> faiss.VectorSearchRequest
	3, // 7: faiss.VectorAPI.Delete:input_type -> faiss.VectorDeletionRequest
	4, // 8: faiss.VectorAPI.Enroll:output_type -> faiss.VectorEnrollmentResponse
	6, // 9: faiss.VectorAPI.Search:output_type -> faiss.VectorSearchResponse
	7, // 10: faiss.VectorAPI.Delete:output_type -> faiss.VectorDeletionResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_services_user_protos_faiss_v1_faiss_proto_init() }
func file_services_user_protos_faiss_v1_faiss_proto_init() {
	if File_services_user_protos_faiss_v1_faiss_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_user_protos_faiss_v1_faiss_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vector); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_user_protos_faiss_v1_faiss_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VectorEnrollmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_user_protos_faiss_v1_faiss_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VectorDeletionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_user_protos_faiss_v1_faiss_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VectorEnrollmentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_user_protos_faiss_v1_faiss_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VectorSearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_user_protos_faiss_v1_faiss_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VectorSearchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_user_protos_faiss_v1_faiss_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VectorDeletionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_user_protos_faiss_v1_faiss_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_user_protos_faiss_v1_faiss_proto_goTypes,
		DependencyIndexes: file_services_user_protos_faiss_v1_faiss_proto_depIdxs,
		EnumInfos:         file_services_user_protos_faiss_v1_faiss_proto_enumTypes,
		MessageInfos:      file_services_user_protos_faiss_v1_faiss_proto_msgTypes,
	}.Build()
	File_services_user_protos_faiss_v1_faiss_proto = out.File
	file_services_user_protos_faiss_v1_faiss_proto_rawDesc = nil
	file_services_user_protos_faiss_v1_faiss_proto_goTypes = nil
	file_services_user_protos_faiss_v1_faiss_proto_depIdxs = nil
}
