package constants

type Activity int
type UserState int
type AdministratorState int
type DeviceAction int
type AdministratorAction int
type UserAction int
type DeviceState int
type ActionState int
type LocationState int
type GroupState int
type RoleType int
type DataUpdatedType int

const (
	ENROLL Activity = iota
	VERIFY
	ROOM_CHECK_IN
	ROOM_CHECK_OUT
	PLAYGROUND_CHECK_IN
	BREAKFAST_CHECK_IN
	LUNCH_CHECK_IN
	DINNER_CHECK_IN
	EVENT_CHECK_IN
	ACCESSED_ROOM
	BREAKFAST_BUY
	LUNCH_BUY
	DINNER_BUY
	PLAYGROUND_BUY
	activityLimit // this will be the last Activity + 1
)

const (
	USER_STATE_ENABLED = iota
	USER_STATE_DISABLED
	USER_STATE_DELETED
)

const (
	ADMINISTRATOR_STATE_ACTIVATED = iota
	ADMINISTRATOR_STATE_DEACTIVATED
	ADMINISTRATOR_STATE_LIMITED
	ADMINISTRATOR_STATE_DELETED
	ADMINISTRATOR_STATE_RESTRICTED
)

const (
	DEVICE_STATE_PENDING DeviceState = iota
	DEVICE_STATE_READY
	DEVICE_STATE_NOT_READY
	DEVICE_STATE_CHARGING
	DEVICE_STATE_MAINTENANCE
	DEVICE_STATE_REMOVED
	DEVICE_STATE_UNKNOWN
	DEVICE_STATE_IN_STORAGE
	DEVICE_STATE_LOW_BATTERY
)

const (
	LOCATION_STATE_SERVING LocationState = iota
	LOCATION_STATE_AVAILABLE
	LOCATION_STATE_UNAVAILABLE
	LOCATION_STATE_HIGHLOAD
	LOCATION_STATE_MAINTAINANCE
	LOCATION_STATE_RESTRICT
)

const (
	DEVICE_ACTION_READY DeviceAction = iota
	DEVICE_ACTION_OVER_HEAT
	DEVICE_ACTION_LOW_BATTERY
	DEVICE_ACTION_UNAUTHORIZED
	DEVICE_ACTION_AUTHORIZED_SUCCESSFULLY
	DEVICE_ACTION_DELETED
	DEVICE_ACTION_UPDATED
	DEVICE_ACTION_REGISTERED
	DEVICE_ACTION_DANGER
	DEVICE_ACTION_BANNED
	DEVICE_ACTION_PREPARING
)

const (
	Administrator_ACTION_LOGIN AdministratorAction = iota
	Administrator_ACTION_GET_TOKEN
	Administrator_ACTION_MODIFY_USER
	Administrator_ACTION_MODIFY_RECORD
)

const (
	USER_ACTION_ENROLL UserAction = iota
	USER_ACTION_VERIFY
)

const (
	ACTION_STATE_SUCCESS ActionState = iota
	ACTION_STATE_CANCEL
	ACTION_STATE_FAIL
	ACTION_STATE_UNKNOWN
)

const (
	GROUP_STATE_ACTIVATED GroupState = iota
	GROUP_STATE_DEACTIVATED
	GROUP_STATE_DELETED
)

const (
	ROLE_TYPE_SYSTEM_USER RoleType = iota
	ROLE_TYPE_FACEID_USER
)

const (
	DATAUPDATED_COMMON DataUpdatedType = iota
	DATAUPDATED_CREATE
	DATAUPDATED_UPDATE
	DATAUPDATED_DELETE
)
