package constants

const (
	MESSAGETYPE_DEVICE_WAITING_FOR_ACTIVATE string = "DEVICE_WAITING_FOR_ACTIVATE"
	MESSAGETYPE_DEVICE_ACTIVATE_REJECTED    string = "DEVICE_ACTIVATE_REJECTED"
	MESSAGETYPE_DEVICE_ACTIVATED            string = "DEVICE_ACTIVATED"
	MESSAGETYPE_DEVICE_DEACTIVATED          string = "DEVICE_DEACTIVATED"
	MESSAGETYPE_DEVICE_CONFIG_UPDATED       string = "DEVICE_DEVICE_CONFIG_UPDATED"
	MESSAGETYPE_USER_VERIFIED               string = "MESSAGETYPE_USER_VERIFIED"
	MESSAGETYPE_MESSAGE_FAILED_TO_DELIVERY  string = "MESSAGE_FAILED_TO_DELIVERY"
)
