package constants

const (
	ADMIN_PERMISSION_ALL                         = "ALL"
	ADMIN_PERMISSION_COMPANY_WRITE               = "COMPANY_WRITE"
	ADMIN_PERMISSION_COMPANY_READ                = "COMPANY_READ"
	ADMIN_PERMISSION_COMPANY_GROUP_WRITE         = "COMPANY_GROUP_WRITE"
	ADMIN_PERMISSION_COMPANY_GROUP_READ          = "COMPANY_GROUP_READ"
	ADMIN_PERMISSION_COMPANY_ADMINISTRATOR_WRITE = "COMPANY_ADMINISTRATOR_WRITE"
	ADMIN_PERMISSION_COMPANY_ADMINISTRATOR_READ  = "COMPANY_ADMINISTRATOR_READ"
	ADMIN_PERMISSION_COMPANY_EMPLOYEE_WRITE      = "COMPANY_EMPLOYEE_WRITE"
	ADMIN_PERMISSION_COMPANY_EMPLOYEE_READ       = "COMPANY_EMPLOYEE_READ"
	ADMIN_PERMISSION_DEVICE_WRITE                = "DEVICE_WRITE"
	ADMIN_PERMISSION_DEVICE_READ                 = "DEVICE_READ"
	ADMIN_PERMISSION_USER_WRITE                  = "USER_WRITE"
	ADMIN_PERMISSION_USER_READ                   = "USER_READ"
	ADMIN_PERMISSION_EVENT_READ                  = "EVENT_READ"

	DEVICE_PERMISSION = "DEVICE_PERMISSION"
)
