// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: services/user/protos/ai_engine/v1/ai_engine.proto

package ai_engine

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusCode int32

const (
	StatusCode_ENGINE_ERROR                      StatusCode = 0
	StatusCode_SUCCESS                           StatusCode = 1
	StatusCode_BAD_IMAGE                         StatusCode = 2
	StatusCode_BAD_VECTOR                        StatusCode = 3
	StatusCode_IMAGE_REGISTERED_FOR_ANOTHER_USER StatusCode = 4
	StatusCode_FOUND                             StatusCode = 5
	StatusCode_NOT_FOUND                         StatusCode = 6
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0: "ENGINE_ERROR",
		1: "SUCCESS",
		2: "BAD_IMAGE",
		3: "BAD_VECTOR",
		4: "IMAGE_REGISTERED_FOR_ANOTHER_USER",
		5: "FOUND",
		6: "NOT_FOUND",
	}
	StatusCode_value = map[string]int32{
		"ENGINE_ERROR":                      0,
		"SUCCESS":                           1,
		"BAD_IMAGE":                         2,
		"BAD_VECTOR":                        3,
		"IMAGE_REGISTERED_FOR_ANOTHER_USER": 4,
		"FOUND":                             5,
		"NOT_FOUND":                         6,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_services_user_protos_ai_engine_v1_ai_engine_proto_enumTypes[0].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_services_user_protos_ai_engine_v1_ai_engine_proto_enumTypes[0]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_services_user_protos_ai_engine_v1_ai_engine_proto_rawDescGZIP(), []int{0}
}

// Face Image
type Image struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// Image ID, managed by other service
	ImageId string `protobuf:"bytes,2,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
}

func (x *Image) Reset() {
	*x = Image{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_user_protos_ai_engine_v1_ai_engine_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_services_user_protos_ai_engine_v1_ai_engine_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_services_user_protos_ai_engine_v1_ai_engine_proto_rawDescGZIP(), []int{0}
}

func (x *Image) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Image) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

// The request to register a user and his/her face images
type ImageEnrollmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// User ID, managed by other service
	UserUid string `protobuf:"bytes,1,opt,name=user_uid,json=userUid,proto3" json:"user_uid,omitempty"` // (Required)
	// One user can have many face images
	Images []*Image `protobuf:"bytes,2,rep,name=images,proto3" json:"images,omitempty"` // (Required)
}

func (x *ImageEnrollmentRequest) Reset() {
	*x = ImageEnrollmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_user_protos_ai_engine_v1_ai_engine_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageEnrollmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageEnrollmentRequest) ProtoMessage() {}

func (x *ImageEnrollmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_user_protos_ai_engine_v1_ai_engine_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageEnrollmentRequest.ProtoReflect.Descriptor instead.
func (*ImageEnrollmentRequest) Descriptor() ([]byte, []int) {
	return file_services_user_protos_ai_engine_v1_ai_engine_proto_rawDescGZIP(), []int{1}
}

func (x *ImageEnrollmentRequest) GetUserUid() string {
	if x != nil {
		return x.UserUid
	}
	return ""
}

func (x *ImageEnrollmentRequest) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

type ImageSearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Images []*Image `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
}

func (x *ImageSearchRequest) Reset() {
	*x = ImageSearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_user_protos_ai_engine_v1_ai_engine_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageSearchRequest) ProtoMessage() {}

func (x *ImageSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_user_protos_ai_engine_v1_ai_engine_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageSearchRequest.ProtoReflect.Descriptor instead.
func (*ImageSearchRequest) Descriptor() ([]byte, []int) {
	return file_services_user_protos_ai_engine_v1_ai_engine_proto_rawDescGZIP(), []int{2}
}

func (x *ImageSearchRequest) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

type ImageEnrollmentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    StatusCode `protobuf:"varint,1,opt,name=code,proto3,enum=ai_engine.StatusCode" json:"code,omitempty"`
	Message string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Optional message from server
}

func (x *ImageEnrollmentResponse) Reset() {
	*x = ImageEnrollmentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_user_protos_ai_engine_v1_ai_engine_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageEnrollmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageEnrollmentResponse) ProtoMessage() {}

func (x *ImageEnrollmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_user_protos_ai_engine_v1_ai_engine_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageEnrollmentResponse.ProtoReflect.Descriptor instead.
func (*ImageEnrollmentResponse) Descriptor() ([]byte, []int) {
	return file_services_user_protos_ai_engine_v1_ai_engine_proto_rawDescGZIP(), []int{3}
}

func (x *ImageEnrollmentResponse) GetCode() StatusCode {
	if x != nil {
		return x.Code
	}
	return StatusCode_ENGINE_ERROR
}

func (x *ImageEnrollmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ImageSearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    StatusCode `protobuf:"varint,1,opt,name=code,proto3,enum=ai_engine.StatusCode" json:"code,omitempty"` // FOUND or NOT_FOUND
	Message string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                      // Optional message from server
	UserUid string     `protobuf:"bytes,4,opt,name=user_uid,json=userUid,proto3" json:"user_uid,omitempty"`       // Empty when user image not found
	ImageId string     `protobuf:"bytes,5,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`       // The image_id of the first mached image
	Score   float64    `protobuf:"fixed64,6,opt,name=score,proto3" json:"score,omitempty"`                        // The matching score for debugging purpose
}

func (x *ImageSearchResponse) Reset() {
	*x = ImageSearchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_user_protos_ai_engine_v1_ai_engine_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageSearchResponse) ProtoMessage() {}

func (x *ImageSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_user_protos_ai_engine_v1_ai_engine_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageSearchResponse.ProtoReflect.Descriptor instead.
func (*ImageSearchResponse) Descriptor() ([]byte, []int) {
	return file_services_user_protos_ai_engine_v1_ai_engine_proto_rawDescGZIP(), []int{4}
}

func (x *ImageSearchResponse) GetCode() StatusCode {
	if x != nil {
		return x.Code
	}
	return StatusCode_ENGINE_ERROR
}

func (x *ImageSearchResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ImageSearchResponse) GetUserUid() string {
	if x != nil {
		return x.UserUid
	}
	return ""
}

func (x *ImageSearchResponse) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *ImageSearchResponse) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_services_user_protos_ai_engine_v1_ai_engine_proto protoreflect.FileDescriptor

var file_services_user_protos_ai_engine_v1_ai_engine_proto_rawDesc = []byte{
	0x0a, 0x31, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x69, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65,
	0x2f, 0x76, 0x31, 0x2f, 0x61, 0x69, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x09, 0x61, 0x69, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x22, 0x36,
	0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x19, 0x0a, 0x08, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x49, 0x64, 0x22, 0x5d, 0x0a, 0x16, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x45,
	0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x19, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x55, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x06, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x69,
	0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x06, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x73, 0x22, 0x3e, 0x0a, 0x12, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x06, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x69,
	0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x06, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x73, 0x22, 0x5e, 0x0a, 0x17, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x45, 0x6e,
	0x72, 0x6f, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x29, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15,
	0x2e, 0x61, 0x69, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xa6, 0x01, 0x0a, 0x13, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x61, 0x69,
	0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x55, 0x69, 0x64, 0x12, 0x19, 0x0a,
	0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x2a, 0x8b,
	0x01, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a,
	0x0c, 0x45, 0x4e, 0x47, 0x49, 0x4e, 0x45, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x12,
	0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09,
	0x42, 0x41, 0x44, 0x5f, 0x49, 0x4d, 0x41, 0x47, 0x45, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x42,
	0x41, 0x44, 0x5f, 0x56, 0x45, 0x43, 0x54, 0x4f, 0x52, 0x10, 0x03, 0x12, 0x25, 0x0a, 0x21, 0x49,
	0x4d, 0x41, 0x47, 0x45, 0x5f, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x45, 0x52, 0x45, 0x44, 0x5f,
	0x46, 0x4f, 0x52, 0x5f, 0x41, 0x4e, 0x4f, 0x54, 0x48, 0x45, 0x52, 0x5f, 0x55, 0x53, 0x45, 0x52,
	0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x05, 0x12, 0x0d, 0x0a,
	0x09, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x06, 0x32, 0xa4, 0x01, 0x0a,
	0x08, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x41, 0x50, 0x49, 0x12, 0x4f, 0x0a, 0x06, 0x45, 0x6e, 0x72,
	0x6f, 0x6c, 0x6c, 0x12, 0x21, 0x2e, 0x61, 0x69, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x69, 0x5f, 0x65, 0x6e, 0x67, 0x69,
	0x6e, 0x65, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x06, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x12, 0x1d, 0x2e, 0x61, 0x69, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65,
	0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x69, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x2d, 0x5a, 0x2b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f,
	0x75, 0x73, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x69, 0x5f, 0x65,
	0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x61, 0x69, 0x5f, 0x65, 0x6e, 0x67, 0x69,
	0x6e, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_user_protos_ai_engine_v1_ai_engine_proto_rawDescOnce sync.Once
	file_services_user_protos_ai_engine_v1_ai_engine_proto_rawDescData = file_services_user_protos_ai_engine_v1_ai_engine_proto_rawDesc
)

func file_services_user_protos_ai_engine_v1_ai_engine_proto_rawDescGZIP() []byte {
	file_services_user_protos_ai_engine_v1_ai_engine_proto_rawDescOnce.Do(func() {
		file_services_user_protos_ai_engine_v1_ai_engine_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_user_protos_ai_engine_v1_ai_engine_proto_rawDescData)
	})
	return file_services_user_protos_ai_engine_v1_ai_engine_proto_rawDescData
}

var file_services_user_protos_ai_engine_v1_ai_engine_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_services_user_protos_ai_engine_v1_ai_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_services_user_protos_ai_engine_v1_ai_engine_proto_goTypes = []interface{}{
	(StatusCode)(0),                 // 0: ai_engine.StatusCode
	(*Image)(nil),                   // 1: ai_engine.Image
	(*ImageEnrollmentRequest)(nil),  // 2: ai_engine.ImageEnrollmentRequest
	(*ImageSearchRequest)(nil),      // 3: ai_engine.ImageSearchRequest
	(*ImageEnrollmentResponse)(nil), // 4: ai_engine.ImageEnrollmentResponse
	(*ImageSearchResponse)(nil),     // 5: ai_engine.ImageSearchResponse
}
var file_services_user_protos_ai_engine_v1_ai_engine_proto_depIdxs = []int32{
	1, // 0: ai_engine.ImageEnrollmentRequest.images:type_name -> ai_engine.Image
	1, // 1: ai_engine.ImageSearchRequest.images:type_name -> ai_engine.Image
	0, // 2: ai_engine.ImageEnrollmentResponse.code:type_name -> ai_engine.StatusCode
	0, // 3: ai_engine.ImageSearchResponse.code:type_name -> ai_engine.StatusCode
	2, // 4: ai_engine.ImageAPI.Enroll:input_type -> ai_engine.ImageEnrollmentRequest
	3, // 5: ai_engine.ImageAPI.Search:input_type -> ai_engine.ImageSearchRequest
	4, // 6: ai_engine.ImageAPI.Enroll:output_type -> ai_engine.ImageEnrollmentResponse
	5, // 7: ai_engine.ImageAPI.Search:output_type -> ai_engine.ImageSearchResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_services_user_protos_ai_engine_v1_ai_engine_proto_init() }
func file_services_user_protos_ai_engine_v1_ai_engine_proto_init() {
	if File_services_user_protos_ai_engine_v1_ai_engine_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_user_protos_ai_engine_v1_ai_engine_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Image); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_user_protos_ai_engine_v1_ai_engine_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageEnrollmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_user_protos_ai_engine_v1_ai_engine_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageSearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_user_protos_ai_engine_v1_ai_engine_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageEnrollmentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_user_protos_ai_engine_v1_ai_engine_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageSearchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_user_protos_ai_engine_v1_ai_engine_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_user_protos_ai_engine_v1_ai_engine_proto_goTypes,
		DependencyIndexes: file_services_user_protos_ai_engine_v1_ai_engine_proto_depIdxs,
		EnumInfos:         file_services_user_protos_ai_engine_v1_ai_engine_proto_enumTypes,
		MessageInfos:      file_services_user_protos_ai_engine_v1_ai_engine_proto_msgTypes,
	}.Build()
	File_services_user_protos_ai_engine_v1_ai_engine_proto = out.File
	file_services_user_protos_ai_engine_v1_ai_engine_proto_rawDesc = nil
	file_services_user_protos_ai_engine_v1_ai_engine_proto_goTypes = nil
	file_services_user_protos_ai_engine_v1_ai_engine_proto_depIdxs = nil
}
