// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: logging.proto

package appsvc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LoggingClient is the client API for Logging service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoggingClient interface {
	AddLog(ctx context.Context, in *AddLogRequest, opts ...grpc.CallOption) (*AddLogResponse, error)
	GetLog(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	GetLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (*GetLogsResponse, error)
	ScheduleReport(ctx context.Context, in *ScheduleReportRequest, opts ...grpc.CallOption) (*ScheduleReportResponse, error)
}

type loggingClient struct {
	cc grpc.ClientConnInterface
}

func NewLoggingClient(cc grpc.ClientConnInterface) LoggingClient {
	return &loggingClient{cc}
}

func (c *loggingClient) AddLog(ctx context.Context, in *AddLogRequest, opts ...grpc.CallOption) (*AddLogResponse, error) {
	out := new(AddLogResponse)
	err := c.cc.Invoke(ctx, "/appsvc.Logging/AddLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loggingClient) GetLog(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, "/appsvc.Logging/GetLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loggingClient) GetLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (*GetLogsResponse, error) {
	out := new(GetLogsResponse)
	err := c.cc.Invoke(ctx, "/appsvc.Logging/GetLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loggingClient) ScheduleReport(ctx context.Context, in *ScheduleReportRequest, opts ...grpc.CallOption) (*ScheduleReportResponse, error) {
	out := new(ScheduleReportResponse)
	err := c.cc.Invoke(ctx, "/appsvc.Logging/ScheduleReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoggingServer is the server API for Logging service.
// All implementations must embed UnimplementedLoggingServer
// for forward compatibility
type LoggingServer interface {
	AddLog(context.Context, *AddLogRequest) (*AddLogResponse, error)
	GetLog(context.Context, *QueryRequest) (*QueryResponse, error)
	GetLogs(context.Context, *GetLogsRequest) (*GetLogsResponse, error)
	ScheduleReport(context.Context, *ScheduleReportRequest) (*ScheduleReportResponse, error)
	mustEmbedUnimplementedLoggingServer()
}

// UnimplementedLoggingServer must be embedded to have forward compatible implementations.
type UnimplementedLoggingServer struct {
}

func (UnimplementedLoggingServer) AddLog(context.Context, *AddLogRequest) (*AddLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddLog not implemented")
}
func (UnimplementedLoggingServer) GetLog(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLog not implemented")
}
func (UnimplementedLoggingServer) GetLogs(context.Context, *GetLogsRequest) (*GetLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLogs not implemented")
}
func (UnimplementedLoggingServer) ScheduleReport(context.Context, *ScheduleReportRequest) (*ScheduleReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScheduleReport not implemented")
}
func (UnimplementedLoggingServer) mustEmbedUnimplementedLoggingServer() {}

// UnsafeLoggingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoggingServer will
// result in compilation errors.
type UnsafeLoggingServer interface {
	mustEmbedUnimplementedLoggingServer()
}

func RegisterLoggingServer(s grpc.ServiceRegistrar, srv LoggingServer) {
	s.RegisterService(&Logging_ServiceDesc, srv)
}

func _Logging_AddLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggingServer).AddLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appsvc.Logging/AddLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggingServer).AddLog(ctx, req.(*AddLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logging_GetLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggingServer).GetLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appsvc.Logging/GetLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggingServer).GetLog(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logging_GetLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggingServer).GetLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appsvc.Logging/GetLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggingServer).GetLogs(ctx, req.(*GetLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logging_ScheduleReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggingServer).ScheduleReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appsvc.Logging/ScheduleReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggingServer).ScheduleReport(ctx, req.(*ScheduleReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Logging_ServiceDesc is the grpc.ServiceDesc for Logging service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Logging_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "appsvc.Logging",
	HandlerType: (*LoggingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddLog",
			Handler:    _Logging_AddLog_Handler,
		},
		{
			MethodName: "GetLog",
			Handler:    _Logging_GetLog_Handler,
		},
		{
			MethodName: "GetLogs",
			Handler:    _Logging_GetLogs_Handler,
		},
		{
			MethodName: "ScheduleReport",
			Handler:    _Logging_ScheduleReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logging.proto",
}
